tap "1password/tap"
tap "buildpacks/tap"
tap "graalvm/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "maciejwalkowiak/brew"
tap "mdogan/zulu"
tap "spring-io/tap"
tap "ubuntu/microk8s"

brew "anyenv"
brew "ansible"
brew "openssl@3"
brew "aws-cdk"
brew "readline"
brew "awscli"
brew "azure-cli"
brew "gmp"
brew "btop"
brew "cmake"
brew "harfbuzz"
brew "tesseract"
brew "cmus"
brew "libyaml"
brew "cocoapods"
brew "coreutils"
brew "ctop"
brew "libssh2"
brew "curl"
brew "dive"
brew "dotnet"
brew "fx"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-flow"
brew "gnupg"
brew "gradle"
brew "graphviz"
brew "groovy"
brew "helm"
brew "htop"
brew "httpie"
brew "kind"
brew "libheif"
brew "imagemagick"
brew "jhipster"
brew "jmeter"
brew "jq"
brew "just"
brew "k9s"
brew "kdoctor"
brew "kotlin"
brew "kubernetes-cli"
brew "libpq"
brew "mackup"
brew "mas"
brew "maven"
brew "midnight-commander"
brew "minikube"
brew "microk8s"
brew "neofetch"
brew "neovim"
brew "openjdk@11"
brew "openjdk@17"
brew "openjdk@21"
brew "php"
brew "pinentry-mac"
brew "qemu"
brew "rustup-init"
brew "speedtest-cli"
brew "subversion"
brew "tealdeer"
brew "telnet"
brew "terraform"
brew "tmux"
brew "trash", link: false
brew "trash-cli"
brew "tree"
brew "yarn"
brew "yh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "pack"
brew "spring-boot"

cask "1password"
cask "1password-cli"
cask "adguard"
cask "alfred"
cask "anydesk"
cask "apparency"
cask "appcleaner"
cask "arc"
cask "brewservicesmenubar"
cask "browserosaurus"
cask "corretto"
cask "corretto11"
cask "corretto17"
cask "corretto8"
cask "daisydisk"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "drawio"
cask "eclipse-jee"
cask "firefox"
cask "figma"
cask "fliqlo"
cask "folx"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-for-powerline"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg"
cask "font-meslo-lg-dz"
cask "font-meslo-lg-nerd-font"
cask "fork"
cask "flameshot"
cask "flutter"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "graalvm-ce-java11"
cask "graalvm-ce-java17"
cask "graalvm-ce-java19"
cask "graalvm-ce-java8"
cask "icons8"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "keystore-explorer"
cask "lens"
cask "meld"
cask "messenger"
cask "microsoft-remote-desktop"
cask "miro"
cask "mongodb-compass"
cask "multipass"
cask "netbeans"
cask "notion"
cask "obs"
cask "obsidian"
cask "openvpn-connect"
cask "postman"
cask "proxyman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "readdle-spark"
cask "rectangle"
cask "redisinsight"
cask "signal"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "springtoolsuite"
cask "sublime-text"
cask "suspicious-package"
cask "telegram"
cask "temurin8"
cask "temurin11"
cask "temurin17"
cask "temurin21"
cask "temurin"
cask "thingsmacsandboxhelper"
cask "todoist"
cask "tower"
cask "utm"
cask "vanilla"
cask "visual-studio-code"
cask "visualvm"
cask "vlc"
cask "vmware-fusion"
cask "webpquicklook"
cask "wechat"
cask "zoom"
cask "zulu-jdk8"
cask "zulu-jdk11"
cask "zulu-jdk17"
cask "zulu-jdk21"
cask "zulu-mc"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "AudioBookBinder", id: 413969927
mas "Battery Health 2", id: 1120214373
mas "CleanMyDrive 2", id: 523620159
mas "Color Picker", id: 1545870783
mas "Dato", id: 1470584107
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "pomodorome", id: 1484801884
mas "ScreenBrush", id: 1233965871
mas "Spark", id: 1176895641
mas "Startup Disk Full Fixer", id: 1346655838
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp Desktop", id: 1147396723
mas "Xcode", id: 497799835
