tap "1password/tap"
tap "buildpacks/tap"
tap "graalvm/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "maciejwalkowiak/brew"
tap "mdogan/zulu"
tap "spring-io/tap"

brew "anyenv"
brew "openssl@3"
brew "aws-cdk"
brew "readline"
brew "awscli"
brew "azure-cli"
brew "gmp"
brew "btop"
brew "cmake"
brew "harfbuzz"
brew "tesseract"
brew "cmus"
brew "libyaml"
brew "cocoapods"
brew "coreutils"
brew "ctop"
brew "libssh2"
brew "curl"
brew "dive"
brew "dotnet"
brew "fx"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-flow"
brew "gnupg"
brew "gradle"
brew "groovy"
brew "helm"
brew "htop"
brew "httpie"
brew "libheif"
brew "imagemagick"
brew "jhipster"
brew "openjdk@17"
brew "jmeter"
brew "jq"
brew "just"
brew "k9s"
brew "kotlin"
brew "kubernetes-cli"
brew "libpq"
brew "mackup"
brew "mas"
brew "maven"
brew "midnight-commander"
brew "minikube"
brew "neofetch"
brew "neovim"
brew "openjdk@11"
brew "php"
brew "pinentry-mac"
brew "qemu"
brew "speedtest-cli"
brew "subversion"
brew "tealdeer"
brew "telnet"
brew "terraform"
brew "tmux"
brew "trash", link: false
brew "trash-cli"
brew "tree"
brew "yarn"
brew "yh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "buildpacks/tap/pack"
brew "spring-io/tap/spring-boot"

cask "1password"
cask "1password-cli"
cask "adguard"
cask "alfred"
cask "anydesk"
cask "apparency"
cask "appcleaner"
cask "brewservicesmenubar"
cask "browserosaurus"
cask "cleanshot"
cask "corretto"
cask "corretto11"
cask "corretto17"
cask "corretto8"
cask "daisydisk"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "drawio"
cask "eclipse-jee"
cask "firefox"
cask "fliqlo"
cask "folx"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-for-powerline"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg"
cask "font-meslo-lg-dz"
cask "font-meslo-lg-nerd-font"
cask "fork"
cask "gimp"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "graalvm-ce-java11"
cask "graalvm-ce-java17"
cask "graalvm-ce-java19"
cask "graalvm-ce-java8"
cask "icons8"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kdiff3"
cask "keka"
cask "keystore-explorer"
cask "lens"
cask "meld"
cask "messenger"
cask "microsoft-remote-desktop"
cask "mongodb-compass"
cask "netbeans"
cask "notion"
cask "obs"
cask "obsidian"
cask "openlens"
cask "openvpn-connect"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "readdle-spark"
cask "rectangle"
cask "redisinsight"
cask "signal"
cask "slack"
cask "smartgit"
cask "sourcetree"
cask "spotify"
cask "springtoolsuite"
cask "sublime-text"
cask "suspicious-package"
cask "telegram"
cask "temurin"
cask "temurin11"
cask "temurin17"
cask "temurin8"
cask "thingsmacsandboxhelper"
cask "ticktick"
cask "tower"
cask "utm"
cask "vagrant"
cask "vagrant-manager"
cask "vanilla"
cask "visual-studio-code"
cask "visualvm"
cask "vlc"
cask "vmware-fusion"
cask "webpquicklook"
cask "zoom"
cask "zulu-jdk11"
cask "zulu-jdk17"
cask "zulu-jdk20"
cask "zulu-jdk8"
cask "zulu-mc"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "AudioBookBinder", id: 413969927
mas "Battery Health 2", id: 1120214373
mas "CleanMyDrive 2", id: 523620159
mas "Color Picker", id: 1545870783
mas "Dato", id: 1470584107
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Outlook", id: 985367838
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "pomodorome", id: 1484801884
mas "ScreenBrush", id: 1233965871
mas "Spark", id: 1176895641
mas "Startup Disk Full Fixer", id: 1346655838
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835

vscode "asciidoctor.asciidoctor-vscode"
vscode "codezombiech.gitignore"
vscode "Dedsec727.jekyll-run"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "gera2ld.markmap-vscode"
vscode "GitHub.github-vscode-theme"
vscode "GitHub.vscode-pull-request-github"
vscode "jasonnutter.search-node-modules"
vscode "k--kato.intellij-idea-keybindings"
vscode "KevinRose.vsc-python-indent"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "mtxr.sqltools"
vscode "naco-siren.gradle-language"
vscode "oderwat.indent-rainbow"
vscode "PKief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "richardwillis.vscode-gradle-extension-pack"
vscode "shengchen.vscode-checkstyle"
vscode "sissel.shopify-liquid"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "vmware.vscode-boot-dev-pack"
vscode "vmware.vscode-spring-boot"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscjava.vscode-spring-boot-dashboard"
vscode "vscjava.vscode-spring-initializr"
vscode "WakaTime.vscode-wakatime"
vscode "wayou.vscode-todo-highlight"
vscode "wholroyd.jinja"
vscode "yzhang.markdown-all-in-one"
vscode "ziyasal.vscode-open-in-github"
