tap "1password/tap"
tap "buildpacks/tap"
tap "graalvm/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "maciejwalkowiak/brew"
tap "mdogan/zulu"
tap "spring-io/tap"
tap "ubuntu/microk8s"
tap "shaunsingh/SFMono-Nerd-Font-Ligaturized"

brew "libyaml"
brew "openssl@3"
brew "readline"
brew "ansible"
brew "anyenv"
brew "gmp"
brew "bash"
brew "bc"
brew "coreutils"
brew "gawk"
brew "gsed"
brew "btop"
brew "cmake"
brew "cmus"
brew "composer"
brew "cocoapods"
brew "coreutils"
brew "ctop"
brew "libssh2"
brew "curl"
brew "dive"
brew "eza"
brew "fx"
brew "fd"
brew "fzf"
brew "libavif"
brew "gd"
brew "gh"
brew "git"
brew "git-flow"
brew "go"
brew "gnupg"
brew "gradle"
brew "graphviz"
brew "groovy"
brew "helm"
brew "htop"
brew "httpie"
brew "lazygit"
brew "libheif"
brew "luarocks"
brew "imagemagick"
brew "jhipster"
brew "jmeter"
brew "jq"
brew "julia"
brew "just"
brew "k9s"
brew "kdoctor"
brew "kind"
brew "kotlin"
brew "kubernetes-cli"
brew "libpq"
brew "mackup"
brew "mas"
brew "maven"
brew "minikube"
brew "neofetch"
brew "neovim"
brew "nowplaying-cli"
brew "podman"
brew "php"
brew "pinentry-mac"
brew "qemu"
brew "ripgrep"
brew "speedtest-cli"
brew "stow"
brew "tealdeer"
brew "telnet"
brew "terraform"
brew "tpm"
brew "tmux"
brew "trash-cli"
brew "tree"
brew "wget"
brew "yarn"
brew "yh"
brew "pack"
brew "spring-boot"
brew "microk8s"

# App's
cask "1password"
cask "1password-cli"
cask "adguard"
cask "alacritty"
cask "alfred"
cask "anydesk"
cask "apparency"
cask "appcleaner"
cask "arc"
cask "daisydisk"
cask "docker"
cask "drawio"
cask "figma"
cask "firefox"
cask "flameshot"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "keka"
cask "kitty" 
cask "miro"
cask "multipass"
cask "netnewswire"
cask "notion"
cask "notion-calendar"
cask "obs"
cask "obsidian"
cask "openvpn-connect"
cask "spotify"
cask "utm"
cask "vlc"
# Messanger's
cask "discord"
cask "slack"
cask "telegram"
cask "viber"
cask "wechat"
cask "zoom"
# Editor's
cask "dbeaver-community"
cask "fork"
cask "lens"
cask "mongodb-compass"
cask "pgadmin4"
cask "podman-desktop"
cask "postman"
cask "proxyman"
cask "pulsar"
cask "redisinsight"
cask "sublime-text"
cask "tower"
cask "visual-studio-code"
cask "warp"
cask "zed"
# Utils
cask "folx"
cask "meld"
cask "fliqlo"
cask "vanilla"
cask "monitorcontrol"
cask "browserosaurus"
cask "brewservicesmenubar"
cask "thingsmacsandboxhelper"
# Quick Look Plugins
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "qlprettypatch"
cask "quicklook-csv"
cask "qlplayground"
cask "webpquicklook"
# Font's
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-for-powerline"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg"
cask "font-meslo-lg-dz"
cask "font-meslo-lg-nerd-font"
cask "font-sf-mono-nerd-font-ligaturized"
# Java: Amazon Corretto releases
cask "corretto8"
cask "corretto11"
cask "corretto17"
cask "corretto21"
cask "corretto"
# Java: Eclipse Temurin releases
cask "temurin8"
cask "temurin11"
cask "temurin17"
cask "temurin21"
cask "temurin"
# Java: GraalVM CE releases
# repository: https://github.com/graalvm/homebrew-tap
cask "graalvm-community-jdk17"
cask "graalvm-community-jdk21"
cask "graalvm-community-jdk22"
# Java: Zulu JDK releases
cask "zulu-jdk8"
cask "zulu-jdk11"
cask "zulu-jdk17"
cask "zulu-jdk21"
cask "zulu"
# Java: IDE's
cask "eclipse-jee"
cask "jetbrains-toolbox"
cask "netbeans"
cask "springtoolsuite"
# Java: Tool's
cask "jmc"
cask "jprofiler"
cask "keystore-explorer"
cask "visualvm"
# Java: Mission Controls
cask "zulu-mc"
# Learning
cask "flutter"

# Mac App Store
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "AudioBookBinder", id: 413969927
mas "Battery Health 2", id: 1120214373
mas "CleanMyDrive 2", id: 523620159
mas "Color Picker", id: 1545870783
mas "Dato", id: 1470584107
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixea", id: 1507782672
mas "pomodorome", id: 1484801884
mas "ScreenBrush", id: 1233965871
mas "Startup Disk Full Fixer", id: 1346655838
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
