"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓█](#e3e5e5)\
$os\
$username\
[](bg:#769ff0 fg:#e3e5e5)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$swift\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#e3e5e5 fg:#090c0c"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#e3e5e5 fg:#090c0c"
style_root = "bg:#e3e5e5 fg:#090c0c"
format = '[ $user]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[c]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[haskell]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol( $version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[line_break]
disabled = true

[character]
disabled = true
