SESSION_NAME="Obsidian"
SESSION_ROOT="$HOME/Workspace/personal/projects"
WINDOW_ROOT="${OBSIDIAN_VAULT:-$HOME/Workspace/personal/obsidian/my-second-brain}"
WINDOW_TITLE="Obsidian"
source "$TMUXIFIER_LAYOUT_PATH/common/project.session.sh"
