require('core.vim.options')
require('core.vim.mappings')

require('core.plugins')
require('core.plugins.colorscheme')
require('core.plugins.lualine')
require('core.plugins.noice')
require('core.plugins.notify')
require('core.plugins.dashboard')
require('core.plugins.lsp_config')
require('core.plugins.completions')
require('core.plugins.telescope')
require('core.plugins.treesitter')
require('core.plugins.gitsigns')
require('core.plugins.whichkey')

require('core.plugins.nvimtree')
